<a href="https://colab.research.google.com/github/Rockzart/Numpy-Pandas/blob/main/pandas_platzi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Crear una lista

In [ ]:
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
listanp = np.array(lista)
listanp

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
type(listanp)

numpy.ndarray

Crear una matriz

In [ ]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## TRABAJANDO CON ÍNDICES ##

---



In [ ]:
listanp

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
listanp[0]

1

In [ ]:
listanp[1] + listanp[2]

5

In [ ]:
matriz[0]

array([1, 2, 3])

In [ ]:
matriz[1,2]

6

In [ ]:
listanp[0:3]

array([1, 2, 3])

In [ ]:
listanp[:6]

array([1, 2, 3, 4, 5, 6])

In [ ]:
listanp[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
listanp[0:6:2]

array([1, 3, 5])

In [ ]:
listanp[-1]

9

In [ ]:
listanp[-3:]

array([7, 8, 9])

In [ ]:
matriz[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])

##TIPOS DE DATOS##

---




Los arrays de NumPy solo pueden contener un tipo de dato, ya que esto es lo que le confiere las ventajas de la optimización de memoria.
El array de Numpy únicamente puede tener un único tipo de datos, no puedo tener valores en int y otros en bool.

La lista declarada al inicio muestra valores que son de tipo int

In [ ]:
listanp.dtype

dtype('int64')

Si queremos usar otro tipo de dato, lo podemos definir en la declaración del array. Los valores muestran un punto decimal.

In [ ]:
listanp = np.array(lista, dtype = 'float')
listanp

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
listanp.dtype

dtype('float64')

Si ya se tiene el array definido, se utiliza el método .astype() para convertir el tipo de dato.

In [ ]:
listanp = listanp.astype(np.int64)
listanp

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
listanp.dtype

dtype('int64')

También podemos convertir los datos en tipo string.

In [ ]:
listanp = listanp.astype(np.str_)
listanp

array(['1', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U21')

In [ ]:
listanp.dtype

dtype('<U21')

También se puede cambiar a tipo booleano recordando que los números diferentes de 0 se convierten en True.

In [ ]:
listaint = [1, 0, 3, 0, 5, 0, 7, 0, 9]
listaint = np.array(listaint)
listabool = listaint.astype(np.bool_)
listabool

array([ True, False,  True, False,  True, False,  True, False,  True])

In [ ]:
listabool.dtype

dtype('bool')

In [ ]:
listabool_to_int = listabool.astype(np.int64)
listabool_to_int

array([1, 0, 1, 0, 1, 0, 1, 0, 1])

In [ ]:
listabool_to_int.dtype

dtype('int64')

## DIMENSIONES ##

---



In [ ]:
scalar = np.array(42)
print(scalar)
print(f"La dimensión del escalar es: ", scalar.ndim)

42
La dimensión del escalar es:  0


In [ ]:
vector = np.array([1, 2, 3])
print(vector)
print(f"La dimensión del vector es: ", vector.ndim)

[1 2 3]
La dimensión del vector es:  1


In [ ]:
matriz = np.array([[1, 2, 3], [4, 5, 6]])
print(matriz)
print(f"La dimensión de la matriz es: ", matriz.ndim)

[[1 2 3]
 [4 5 6]]
La dimensión de la matriz es:  2


In [ ]:
tensor = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],[[13, 13, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]]])
print(tensor)
print(f"La dimensión del tensor es: ", tensor.ndim)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 13 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]
La dimensión del tensor es:  3


**Agregar o eliminar dimensiones**

Se puede definir el número de dimensiones desde la declaración del array

In [ ]:
vector = np.array([1, 2, 3], ndmin = 10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

Se pueden expandir dimensiones a los array ya existentes con expand_dims(). Axis = 0 hace referencia a las filas, mientras que axis = 1 a las columnas.

In [ ]:
expand = np.expand_dims(np.array([1, 2, 3]), axis = 0)
print(expand)
expand.ndim

[[1 2 3]]


2

Remover/comprimir las dimensiones a las que se considera que debe tener el array, eliminando las que no están siendo usadas.

In [ ]:
print(vector, vector.ndim)
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1


## CREACIÓN DE ARRAYS ##

---



Este método de NumPy nos permite generar arrays sin definir previamente una lista

In [ ]:
np.arange(0, 20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((10, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

np.linspace() permite generar una array definiendo un inicio, un final y cuantos datos se van a generar, distribuypendolos de forma normalizada.

In [ ]:
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

np.eye() crea una matriz diagonal.

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Para generar números aleatorios se usa el método np.random.rand()

In [ ]:
np.random.rand(5)

array([0.58348289, 0.72965095, 0.20560158, 0.44216908, 0.51461046])

In [ ]:
np.random.rand(5, 5)

array([[0.08308334, 0.09060749, 0.48282273, 0.26403309, 0.72928788],
       [0.82423722, 0.19422322, 0.64163507, 0.68686153, 0.21902794],
       [0.5276864 , 0.92084547, 0.62151786, 0.74006676, 0.70670587],
       [0.80767663, 0.26754387, 0.38477817, 0.59044383, 0.75648293],
       [0.28961577, 0.79694329, 0.04889054, 0.03165547, 0.56294764]])

NumPy nos permite también generar números enteros. En este caso números enteros entre el 1 y 16

In [ ]:
np.random.randint(1, 16)

8

También podemos llevarlos a una estructura definida.

In [ ]:
np.random.randint(1, 16, 10)

array([ 7, 10,  3,  6,  5, 11, 13,  3, 10, 13])

In [ ]:
np.random.randint(1, 16, (5, 5))

array([[ 8, 13,  7,  7, 10],
       [ 5, 15,  9,  5,  6],
       [ 4, 15, 12,  5,  2],
       [11,  5, 12, 12, 14],
       [ 2,  9,  8,  5, 15]])

## SHAPE Y RESHAPE ##

---



Shape indica las dimensiones del arreglo.

In [ ]:
arr = np.random.randint(1, 10, (3, 2))
print(arr)
print(f"La forma del array es: ", arr.shape)

[[1 8]
 [4 8]
 [7 9]]
La forma del array es:  (3, 2)


Reshape es un comando para cambiar la forma en que se estableció el array

In [ ]:
arr.reshape(1, 6)

array([[1, 8, 4, 8, 7, 9]])

In [ ]:
arr.reshape(2, 3)

array([[1, 8, 4],
       [8, 7, 9]])

In [ ]:
np.reshape(arr, (1, 6))

array([[1, 8, 4, 8, 7, 9]])

Esto es como lo hace el lenguaje C

In [ ]:
np.reshape(arr, (2, 3), 'C')

array([[1, 8, 4],
       [8, 7, 9]])

Esto es como lo hace el lenguaje Fortrand

In [ ]:
np.reshape(arr, (2, 3), 'F')

array([[1, 7, 8],
       [4, 8, 9]])

Esto es como lo hace la forma en que está optimizado nuestro pc que es equivalente a C

In [ ]:
np.reshape(arr, (2, 3), 'A')

array([[1, 8, 4],
       [8, 7, 9]])

## FUNCIONES PRINCIPALES ##

---



In [ ]:
arreglo = np.random.randint(1, 20, 10)
print(arreglo)

[ 5 15 16  1  5  3  6  5  3 18]


In [ ]:
matriz = arreglo.reshape(2, 5)
print(matriz)

[[ 1  3 11  6  1]
 [13 17  5 15  6]]


La función .max devuelve el valor máximo en un array o matriz

In [ ]:
arreglo.max()

18

In [ ]:
matriz.max()

17

Para saber cuál es el valor máximo por cada fila se incluye el valor 1 entre paréntesis.

In [ ]:
matriz.max(1)

array([11, 17])

Para saber cuál es el valor máximo por cada columna se incluye el valor 0 entre paréntesis.

In [ ]:
matriz.max(0)

array([13, 17, 11, 15,  6])

Se usa .argmax() para conocer la posición del elemento

In [ ]:
arreglo.argmax()

9

In [ ]:
matriz.argmax()

6

In [ ]:
matriz.argmax(0)

array([1, 1, 0, 1, 1])

También se tiene la función .min para conocer el valor mínimo

In [ ]:
arreglo.min()

1

In [ ]:
arreglo.argmin()

3

In [ ]:
matriz.min()

1

In [ ]:
matriz.min(0)

array([1, 3, 5, 6, 1])

In [ ]:
matriz.min(1)

array([1, 5])

In [ ]:
matriz.argmin()

0

In [ ]:
matriz.argmin(0)

array([0, 0, 1, 0, 0])

In [ ]:
matriz.argmin(1)

array([0, 2])

Podemos saber la diferencia entre el valor más bajo con el más alto

In [ ]:
arreglo.ptp()

17

In [ ]:
matriz.ptp()

16

In [ ]:
matriz.ptp(0)

array([12, 14,  6,  9,  5])

**Funciones estadísticas**

In [ ]:
arreglo

array([ 5, 15, 16,  1,  5,  3,  6,  5,  3, 18])

In [ ]:
np.percentile(arreglo, 50)

5.0

In [ ]:
np.percentile(arreglo, 0)

1.0

In [ ]:
np.percentile(arreglo, 100)

18.0

In [ ]:
np.median(arreglo)

5.0

In [ ]:
arreglo.sort()
arreglo

array([ 1,  3,  3,  5,  5,  5,  6, 15, 16, 18])

In [ ]:
arreglo.mean()

7.7

In [ ]:
np.std(arreglo)

5.848931526355904

In [ ]:
np.var(arreglo)

34.21

In [ ]:
np.median(matriz)

6.0

In [ ]:
np.median(matriz, 0) # Esto calcula la mediana de cada columna

array([ 7. , 10. ,  8. , 10.5,  3.5])

In [ ]:
np.median(matriz, 1) # Esto calcula la mediana de cada fila

array([ 3., 13.])

**Concatenar**

In [ ]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [ ]:

b = np.array([5, 6])
b

array([5, 6])

Antes de concatenar hay que modificar la dimensión de b

In [ ]:
b = np.expand_dims(b, axis = 0)

In [ ]:
np.concatenate((a, b), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

Para concatenar por columna se transpone b dado que es un array de una fila

In [ ]:
np.concatenate((a, b.T), axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])

In [ ]:
b.T

array([[5],
       [6]])

## COPY ##

---



In [ ]:
array = np.arange(0, 10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
fragmento = array[0:6]
fragmento

array([0, 1, 2, 3, 4, 5])

Se modifica el fragmento del array pero al llamar el array original también se modificó

In [ ]:
fragmento[:] = 0
fragmento

array([0, 0, 0, 0, 0, 0])

In [ ]:
array

array([0, 0, 0, 0, 0, 0, 6, 7, 8, 9])

.copy() nos permite copiar un array de NumPy en otra variable de tal forma que al modificar el nuevo array los cambios no se vean reflejados en array original.

In [ ]:
array_copy = array.copy()
array_copy

array([0, 0, 0, 0, 0, 0, 6, 7, 8, 9])

In [ ]:
array_copy[:] = 100
array_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [ ]:
array

array([0, 0, 0, 0, 0, 0, 6, 7, 8, 9])

## CONDICIONES ##

---



In [ ]:
array = np.linspace(1, 10, 10, dtype = 'int')
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
condicion = array > 5
condicion

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
array[condicion]

array([ 6,  7,  8,  9, 10])

In [ ]:
array[array > 5]

array([ 6,  7,  8,  9, 10])

In [ ]:
array[(array > 5) & (array < 9)]

array([6, 7, 8])

In [ ]:
array[array > 5] = 99
array

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99])

In [ ]:
array[array == 99]

array([99, 99, 99, 99, 99])

## OPERACIONES ##

---



Multiplicar una lista en Python se entiende que se quiere duplicar la información. Cosa que no buscamos.

In [ ]:
lista = [1, 2, 3, 4, 5]
lista

[1, 2, 3, 4, 5]

In [ ]:
lista * 2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [ ]:
array = np.arange(0, 10)
array2 = array.copy()

In [ ]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
array * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
array + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
1 / array

<ipython-input-90-4f1f9cd9a334>:1: RuntimeWarning: divide by zero encountered in divide
  1 / array


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
array ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
array + array2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
array * array2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
matriz = array.reshape(2, 5)
matriz_copy = matriz.copy()

In [ ]:
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
matriz + matriz_copy

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [ ]:
matriz * matriz_copy

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [ ]:
matriz - matriz_copy

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
matriz_copy.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [ ]:
np.matmul(matriz, matriz_copy.T)

array([[ 30,  80],
       [ 80, 255]])